version: "3.5"

services:
  web:
    image: "getthatjob:latest"
    ports:
      - "80:4000" # In our .env file above, we chose port 4000
    env_file:
      - config/docker.env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - config/docker.env
